version: "3.2"

services:

  # Database
  cadys_database:
    image: postgres:10.1
    command: postgres -c 'max_connections=250'
    restart: always
    environment:
      POSTGRES_USER: new_app
      POSTGRES_PASSWORD: new_app
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

  # Adminer
  adminer:
    image: adminer
    restart: always
    depends_on:
      - cadys_database
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5095:8080
    networks:
      - app-network

  # API container
  cadys_api:
    container_name: cadys
    build: ./
    volumes:
      - ./:/webapp
    ports:
      - 5030:80
    depends_on:
      - cadys_database
    restart: always
    networks:
      - app-network

# Networks
networks:
  app-network:

#volumes
volumes:
  db:
    driver: local
