apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cadys-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Cadys
  template:
    metadata:
      labels:
        app: Cadys
    spec:
      containers:
        - name: Cadys-container
          image: Cadys-app:latest
          ports:
            - containerPort: 3000

          # Bloc de sécurité à analyser
          securityContext:
            runAsNonRoot: True
            allowPrivilegeEscalation: true
